import type { Metadata } from 'next';
import { GFS_Didot } from 'next/font/google';
import './globals.css';

import Navbar from '../components/Navbar/Navbar';
import { ThemeContextProvider } from '../context/ThemeContext';

const didot = GFS_Didot({ subsets: ['greek'], weight: '400' });

export const metadata: Metadata = {
  title: 'Blog Project By NextJS App Router Version',
  description: 'Generated by NextJS App Router',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={didot.className}>
        <ThemeContextProvider>
          <div className="container">
            <Navbar />
            {children}
          </div>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
