import Head from 'next/head';
import Banner from '../components/Banner';
import Posts from '../components/Posts';
import styles from '../styles/Home.module.css';
import Image from 'next/image';
import { Facebook, Pinterest, Twitter, Instagram } from '@mui/icons-material';
import { Pagination } from '@mui/material';
import { Stack } from '@mui/material';
import React, { useEffect, useState } from 'react';
import axios from 'axios';

export default function Home({ ps }: any) {
  const [posts, setPosts] = useState([]);
  const [count, setCount] = useState<number>();
  const [selectedPost, setSelectedPost] = useState<any>();

  console.log(posts);
  console.log(count);
  console.log(selectedPost);

  useEffect(() => {
    setPosts(ps);
    setCount(Math.ceil(ps?.length / 4));
    setSelectedPost([ps[0], ps[1], ps[2], ps[3]]);
  }, []);

  const handleTotal = () => {};

  const handleChange = () => {};

  const handleCatName = () => {};

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
        <link
          rel='stylesheet'
          href='https://fonts.googleapis.com/icon?family=Material+Icons'
        />

        <link
          rel='stylesheet'
          href='https://unpkg.com/react-quill@1.3.3/dist/quill.snow.css'
        />
        <script
          src='https://unpkg.com/react@16/umd/react.development.js'
          // @ts-ignore
          crossorigin
        ></script>
        <script
          src='https://unpkg.com/react-dom@16/umd/react-dom.development.js'
          // @ts-ignore
          crossorigin
        ></script>
        <script src='https://unpkg.com/react-quill@1.3.3/dist/react-quill.js'></script>
        <script src='https://unpkg.com/babel-standalone@6/babel.min.js'></script>
        <script type='text/babel' src='/my-scripts.js'></script>
      </Head>
      <Banner />
      <button className={styles.totalBtn} onClick={handleTotal}>
        TOTAL
      </button>
      <input
        className={styles.searchInput}
        type='text'
        placeholder='Searching Posts...'
      />
      <div className={styles.container}>
        <Posts selectedPost={selectedPost} />
        <div className={styles.sidebar}>
          <header>About Me</header>
          <div className={styles.imgBox}>
            <Image
              alt='sidebarImg'
              width={30}
              height={30}
              src={'/imgs/charina.gif'}
            />
            <p>Front-End, Back-End, Web Developer</p>
            <p>Sharing My Value and Knowledge For Others</p>
          </div>
          <header className={styles.catHead}>CATEGORIES</header>
          <div className={styles.categoriesBox}>
            <span onClick={handleCatName}>HTML / Git</span>
            <span onClick={handleCatName}>CSS</span>
            <span onClick={handleCatName}>JavaScript</span>
            <span onClick={handleCatName}>Front-End</span>
            <span onClick={handleCatName}>Back-End</span>
            <span onClick={handleCatName}>TypeScript</span>
            <span onClick={handleCatName}>Game</span>
            <span onClick={handleCatName}>Book / Learn</span>
          </div>
          <footer>FOLLOW US</footer>
          <div className={styles.logoBox}>
            <Facebook />
            <Twitter />
            <Pinterest />
            <Instagram />
          </div>
        </div>
      </div>
      <Stack spacing={2} direction='row' justifyContent={'center'}>
        <Pagination count={count} color='primary' onChange={handleChange} />
      </Stack>
    </>
  );
}

export const getServerSideProps = async () => {
  const res = await axios.get(`https://api.lsevina126.asia/posts`);
  return {
    props: {
      ps: res.data.reverse(),
    },
  };
};
