import Head from 'next/head';
import Banner from '../components/Banner';
import Posts from '../components/Posts';
import styles from '../styles/Home.module.css';
import Image from 'next/image';
import { Facebook, Pinterest, Twitter, Instagram } from '@mui/icons-material';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
        <link
          rel='stylesheet'
          href='https://fonts.googleapis.com/icon?family=Material+Icons'
        />

        <link
          rel='stylesheet'
          href='https://unpkg.com/react-quill@1.3.3/dist/quill.snow.css'
        />
        <script
          src='https://unpkg.com/react@16/umd/react.development.js'
          // @ts-ignore
          crossorigin
        ></script>
        <script
          src='https://unpkg.com/react-dom@16/umd/react-dom.development.js'
          // @ts-ignore
          crossorigin
        ></script>
        <script src='https://unpkg.com/react-quill@1.3.3/dist/react-quill.js'></script>
        <script src='https://unpkg.com/babel-standalone@6/babel.min.js'></script>
        <script type='text/babel' src='/my-scripts.js'></script>
      </Head>
      <Banner />
      <button className={styles.totalBtn}>TOTAL</button>
      <div className={styles.container}>
        <Posts />
        <div className={styles.sidebar}>
          <header>About Me</header>
          <div className={styles.imgBox}>
            <Image
              alt='sidebarImg'
              width={30}
              height={30}
              src={'/imgs/charina.gif'}
            />
            <p>Front-End, Back-End, Web Developer</p>
            <p>Sharing My Value and Knowledge For Others</p>
          </div>
          <header className={styles.catHead}>CATEGORIES</header>
          <div className={styles.categoriesBox}>
            <span>HTML / GIT</span>
            <span>CSS</span>
            <span>JavaScript</span>
            <span>Front-End</span>
            <span>Back-End</span>
            <span>TypeScript</span>
            <span>Game</span>
            <span>Book / Learn</span>
          </div>
          <footer>FOLLOW US</footer>
          <div className={styles.logoBox}>
            <Facebook />
            <Twitter />
            <Pinterest />
            <Instagram />
          </div>
        </div>
      </div>
    </>
  );
}
